name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # You can change this to match your branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build the Docker image
        run: docker build -t your-username/your-repo-name:latest .

      - name: Push the Docker image to Docker Hub
        run: docker push your-username/your-repo-name:latest
